import { Transaction } from '../types/transaction'
import { Goal } from '../types/goal'
import { CreditCard } from '../types/creditCard'
import { BankAccount } from '../types/bankAccount'
import { FamilyMember } from '../types/familyMember'

// Membros da família
export const mockFamilyMembers: FamilyMember[] = [
  {
    id: 'member-1',
    name: 'Felipe Oliveira',
    role: 'Pai',
    avatar: null,
    monthlyIncome: 8000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member-2',
    name: 'Maria Silva',
    role: 'Mãe',
    avatar: null,
    monthlyIncome: 6000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'member-3',
    name: 'João Marte',
    role: 'Filho',
    avatar: null,
    monthlyIncome: 0,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Contas bancárias
export const mockBankAccounts: BankAccount[] = [
  {
    id: 'account-1',
    name: 'Nubank Conta',
    type: 'checking',
    holderId: 'member-1',
    balance: 5000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'account-2',
    name: 'Inter Conta',
    type: 'checking',
    holderId: 'member-2',
    balance: 3000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Cartões de crédito
export const mockCreditCards: CreditCard[] = [
  {
    id: 'card-1',
    name: 'Nubank Mastercard',
    holderId: 'member-1',
    limit: 5000,
    currentBill: 120,
    closingDay: 10,
    dueDay: 10,
    theme: 'black',
    lastDigits: '5897',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'card-2',
    name: 'Inter Visa',
    holderId: 'member-2',
    limit: 10000,
    currentBill: 2300,
    closingDay: 21,
    dueDay: 21,
    theme: 'lime',
    lastDigits: '5897',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'card-3',
    name: 'Picpay',
    holderId: 'member-1',
    limit: 20000,
    currentBill: 17000,
    closingDay: 12,
    dueDay: 12,
    theme: 'white',
    lastDigits: '5897',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Objetivos
export const mockGoals: Goal[] = [
  {
    id: 'goal-1',
    title: 'Viagem para Europa',
    description: 'Economizar para viagem de férias',
    targetAmount: 50000,
    currentAmount: 15000,
    deadline: new Date('2024-12-31'),
    status: 'active',
    memberId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'goal-2',
    title: 'Reserva de Emergência',
    description: '6 meses de despesas',
    targetAmount: 84000,
    currentAmount: 42000,
    deadline: null,
    status: 'active',
    memberId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// Transações
const now = new Date()
const getDate = (daysAgo: number) => {
  const date = new Date(now)
  date.setDate(date.getDate() - daysAgo)
  return date
}

export const mockTransactions: Transaction[] = [
  // Receitas
  {
    id: 'trans-1',
    type: 'income',
    amount: 8000,
    description: 'Salário',
    category: 'Salário',
    date: getDate(5),
    accountId: 'account-1',
    memberId: 'member-1',
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
    createdAt: getDate(5),
    updatedAt: getDate(5),
  },
  {
    id: 'trans-2',
    type: 'income',
    amount: 6000,
    description: 'Salário',
    category: 'Salário',
    date: getDate(3),
    accountId: 'account-2',
    memberId: 'member-2',
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
    createdAt: getDate(3),
    updatedAt: getDate(3),
  },
  // Despesas
  {
    id: 'trans-3',
    type: 'expense',
    amount: 4000,
    description: 'Aluguel',
    category: 'Moradia',
    date: getDate(10),
    accountId: 'account-1',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
    createdAt: getDate(10),
    updatedAt: getDate(10),
  },
  {
    id: 'trans-4',
    type: 'expense',
    amount: 2000,
    description: 'Supermercado',
    category: 'Alimentação',
    date: getDate(7),
    accountId: 'card-1',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: false,
    isPaid: true,
    createdAt: getDate(7),
    updatedAt: getDate(7),
  },
  {
    id: 'trans-5',
    type: 'expense',
    amount: 1500,
    description: 'Compras no mercado',
    category: 'Alimentação',
    date: getDate(4),
    accountId: 'card-2',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: false,
    isPaid: true,
    createdAt: getDate(4),
    updatedAt: getDate(4),
  },
  {
    id: 'trans-6',
    type: 'expense',
    amount: 120,
    description: 'Academia',
    category: 'Saúde',
    date: getDate(2),
    accountId: 'card-1',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
    createdAt: getDate(2),
    updatedAt: getDate(2),
  },
  {
    id: 'trans-7',
    type: 'expense',
    amount: 100,
    description: 'Conta de água',
    category: 'Manutenção',
    date: getDate(1),
    accountId: 'account-1',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
    createdAt: getDate(1),
    updatedAt: getDate(1),
  },
  {
    id: 'trans-8',
    type: 'expense',
    amount: 150,
    description: 'Conta de Luz',
    category: 'Manutenção',
    date: getDate(1),
    accountId: 'account-1',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: true,
    isPaid: true,
    createdAt: getDate(1),
    updatedAt: getDate(1),
  },
  {
    id: 'trans-9',
    type: 'expense',
    amount: 750,
    description: 'Passeio no parque',
    category: 'Lazer',
    date: getDate(1),
    accountId: 'card-3',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'completed',
    isRecurring: false,
    isPaid: true,
    createdAt: getDate(1),
    updatedAt: getDate(1),
  },
  // Despesas pendentes
  {
    id: 'trans-10',
    type: 'expense',
    amount: 154,
    description: 'Conta de Luz',
    category: 'Manutenção',
    date: new Date(now.getFullYear(), now.getMonth(), 21),
    accountId: 'card-1',
    memberId: null,
    installments: 1,
    currentInstallment: 1,
    status: 'pending',
    isRecurring: true,
    isPaid: false,
    createdAt: getDate(30),
    updatedAt: getDate(30),
  },
]
